# Site settings
title: Dinh Hoang Long's Blog
email: dinhhoanglong91@gmail.com
description: Dinh Hoang Long's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "dinhhoanglong91.github.io" # the base hostname & protocol for your site
twitter_username: dinhhoanglong91
github_username: dinhhoanglong91

# Default setting
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      category: post

# Build settings
markdown: kramdown
sass:
    style: compressed
gems:
  - jekyll-coffeescript
